[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tt-boltz"
version = "0.1"
description = "Boltz-2 implementation for inference on Tenstorrent Blackhole or Wormhole"
dependencies = [
    "torch",
    "numpy",
    "rdkit",
    "requests",
    "pandas",
    "einops",
    "einx",
    "mashumaro",
    "modelcif",
    "click",
    "pyyaml",
    "biopython",
    "scipy",
    "numba",
    "gemmi",
    "scikit-learn",
    "chembl_structure_pipeline",
    "tqdm",
    "pytest",
    "omegaconf",
    "flask",
]

[project.scripts]
tt-boltz = "tt_boltz.main:cli"

[tool.setuptools]
packages = ["tt_boltz"]

[tool.pytest.ini_options]
testpaths = ["tests"]
